import { Header } from '@/components/Header/Header'
import './globals.scss'
import '../styles/text.scss'
import '../styles/container.scss'
import type { Metadata } from 'next'
import { Footer } from '@/components/Footer/Footer'
import { montserratFont, playfairDisplay } from './fonts'
import clsx from 'clsx'

export const metadata: Metadata = {
  title: 'Grandma Jazz',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(montserratFont.variable, playfairDisplay.variable)}>
        <Header />
        
        <main>
          {children}
        </main>

        <Footer />
      </body>
    </html>
  )
}
